import xwaf.utils.configs as config_utils


def options(ctx):
    ctx.add_option('--config', action='store', default='')


def configure(conf):
    def make_config(name, flags):
        conf.setenv(name)
        conf.load('xwaf.compiler_xcc')
        conf.env.XCC_FLAGS = flags

    for key, value in CONFIGS.iteritems():
        make_config(key, value)


def build(bld):
    if not config_utils.check_build_config(bld, CONFIGS):
        return

    bld.env.PROJECT_ROOT = '../../..'

    depends_on = ['lib_mic_array']

    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    bld.env.XSCOPE = 'config.xscope'

    prog = bld.program(depends_on=depends_on)


CONFIGS = {
    'CH4': ['-O2', '-g', '-Wno-timing', '-DTEST_MODE', '-DCHANNELS=4'],
    'CH8': ['-O2', '-g', '-Wno-timing', '-DTEST_MODE', '-DCHANNELS=8'],
}

config_utils.register_configs(CONFIGS)
