// Copyright 2020-2021 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
// Autogenerated by make_mic_dual_stage_3_coeffs.c

#include "fir_coefs.h"

typedef const int mic_dual_third_stage_coef_t[THIRD_STAGE_COEFS_PER_STAGE];

extern mic_dual_third_stage_coef_t g_third_stage_div_2_fir_dual[2];
extern mic_dual_third_stage_coef_t g_third_stage_div_4_fir_dual[4];
extern mic_dual_third_stage_coef_t g_third_stage_div_6_fir_dual[6];
extern mic_dual_third_stage_coef_t g_third_stage_div_8_fir_dual[8];
extern mic_dual_third_stage_coef_t g_third_stage_div_12_fir_dual[12];
