// Copyright 2019-2021 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

//This program takes the coeffs for normal mic_array and generates a version for mic_dual
//It removes the repetition which mic_dual inner loop doesn't need and 8-byte aligns them so we can use stdd/ldd.
//Bonus: we also save just over 1kB of memory..

//To make this do:
// cc make_mic_dual_stage_3_coefs.c fir_coefs.c; ./a.out

#include <stdio.h>
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include "fir_coefs.h" //From lib_mic_array to access const int g_third_stage_div_N_fir[]

#define MAX_DECIMATION_FACTOR 12

int main(void)
{
    FILE *c_file;
    FILE *h_file;
    time_t timer;
    struct tm *tm_info;
    char year[5];
    char c_file_name[] = "fir_coefs_dual.c";
    char h_file_name[] = "fir_coefs_dual.h";

    const int *fir_coefs[7] = {
            0,
            g_third_stage_div_2_fir,
            g_third_stage_div_4_fir,
            g_third_stage_div_6_fir,
            g_third_stage_div_8_fir,
            0,
            g_third_stage_div_12_fir
    };

    c_file = fopen(c_file_name, "w");
    if (c_file == NULL)
    {
        printf("Error trying to write file %s!", c_file_name);
        exit(1);
    }
    h_file = fopen(h_file_name, "w");
    if (c_file == NULL)
    {
        printf("Error trying to write file %s!", h_file_name);
        exit(1);
    }


    printf("Writing dual coeffs to %s and %s\n", c_file_name, h_file_name);

    time(&timer);
    tm_info = localtime(&timer);
    strftime(year, 5, "%Y", tm_info);
    fprintf(c_file, "// Copy" "right 2019-%s XMOS LIMITED.\n", year);
    fprintf(c_file, "// This Software is subject to the terms of the XMOS Public Licence: Version 1.\n");
    fprintf(c_file, "// Autogenerated by make_mic_dual_stage_3_coeffs.c\n\n");
    fprintf(h_file, "// Copy" "right 2019-%s XMOS LIMITED.\n", year);
    fprintf(h_file, "// This Software is subject to the terms of the XMOS Public Licence: Version 1.\n");
    fprintf(h_file, "// Autogenerated by make_mic_dual_stage_3_coeffs.c\n\n");

    fprintf(h_file, "#include \"fir_coefs.h\"\n\n");
    fprintf(c_file, "#include \"%s\"\n\n", h_file_name);

    fprintf(h_file, "typedef const int mic_dual_third_stage_coef_t[THIRD_STAGE_COEFS_PER_STAGE];\n\n");

    for (int df = 2; df <= MAX_DECIMATION_FACTOR; df += 2) {
        if (df == 10) {
            continue;
        }

        fprintf(c_file, "mic_dual_third_stage_coef_t g_third_stage_div_%d_fir_dual[%d] __attribute__((aligned(8))) = {\n", df, df);
        fprintf(h_file, "extern mic_dual_third_stage_coef_t g_third_stage_div_%d_fir_dual[%d];\n", df, df);

        for (int ph = df - 1; ph >= 0; ph--) {
            fprintf(c_file, "// Phase %d\n{", ph);
            const int *ptr = &fir_coefs[df / 2][(df - 1 - ph) * 63];
            for (int i = 0; i < THIRD_STAGE_COEFS_PER_STAGE; i++) {
                fprintf(c_file, "0x%08x, ", ptr[i]);
            }
            fprintf(c_file, "},\n");
        }
        fprintf(c_file, "};\n\n");
    }

    fclose(c_file);
    fclose(h_file);
}
