#pragma once



#define AUDIO_BUFFER_SAMPLES       17
#define APP_AUDIO_PIPELINE_SAMPLE_RATE   16000
#define APP_I2S_AUDIO_SAMPLE_RATE   APP_AUDIO_PIPELINE_SAMPLE_RATE
#define MIC_ARRAY_CLK1  XS1_CLKBLK_1
#define MIC_ARRAY_CLK2  XS1_CLKBLK_2
