TARGET = SLICEKIT-X200
APP_NAME = 
USED_MODULES = lib_i2c(>=4.0.0) lib_i2s(>=2.2.0) lib_dsp(>=3.0.0) lib_mic_array(>=3.0.0) lib_mic_array_board_support(>=2.1.0)
XCC_FLAGS = -O2 -g -report -fxscope

XCORE_ARM_PROJECT = 0
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
