
def configure(conf):
    conf.load('xwaf.compiler_xcc')

def build(bld):
    bld.env.XCC_FLAGS = ['-O3', '-g']
    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'

    depends_on = ['lib_mic_array']
    prog = bld.program(depends_on=depends_on)
