def configure(conf):
    conf.load('xwaf.compiler_xcc')


def build(bld):
    bld.env.XCC_FLAGS = ['-O2', '-g', '-report', '-Wno-timing']
    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    bld.env.XSCOPE = 'config.xscope'
    bld.env.PROJECT_ROOT = '../../..'

    depends_on = ['lib_mic_array']
    prog = bld.program(depends_on=depends_on)
