import xwaf.utils.configs as config_utils


def options(ctx):
    ctx.add_option('--config', action='store', default='')


def configure(conf):
    def make_config(name, flags):
        conf.setenv(name)
        conf.load('xwaf.compiler_xcc')
        conf.env.XCC_FLAGS = flags

    for key, value in CONFIGS.iteritems():
        make_config(key, value)


def build(bld):
    if not config_utils.check_build_config(bld, CONFIGS):
        return

    bld.env.PROJECT_ROOT = '../../..'

    depends_on = ['lib_mic_array']

    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    bld.env.XSCOPE = 'config.xscope'

    prog = bld.program(depends_on=depends_on)


CONFIGS = {
    'FRONTEND_8BIT_4CH':
    ['-O2', '-g', '-DTEST_MODE', '-DFRONTEND_8BIT_4CH', '-DTEST_MODE'],
    'FRONTEND_8BIT_8CH':
    ['-O2', '-g', '-DTEST_MODE', '-DFRONTEND_8BIT_8CH', '-DTEST_MODE'],
    'FRONTEND_8BIT_4CH_CHANREORDER': [
        '-O2', '-g', '-DTEST_MODE', '-DFRONTEND_8BIT_4CH', '-DTEST_MODE',
        '-DCHANNEL_REORDER_TEST'
    ],
    'BACKEND': ['-O2', '-g', '-DTEST_MODE', '-DBACKEND'],
    'FRONTEND_8BIT_8CH_CHANREORDER': [
        '-O2', '-g', '-DTEST_MODE', '-DFRONTEND_8BIT_8CH', '-DTEST_MODE',
        '-DCHANNEL_REORDER_TEST'
    ],
}

config_utils.register_configs(CONFIGS)
