#pragma once


#define N_MICS  2


#define APP_AUDIO_CLOCK_FREQUENCY        24576000
// #define APP_PDM_CLOCK_FREQUENCY          3072000
#define APP_AUDIO_PIPELINE_SAMPLE_RATE   16000

// #define APP_PIPELINE_FRAME_ADVANCE       1

#define APP_I2S_AUDIO_SAMPLE_RATE   APP_AUDIO_PIPELINE_SAMPLE_RATE
